#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🐶 타입 검사 및 lint 적용을 시작합니다..."

if npx tsc --noEmit --project tsconfig.app.json; then
  echo "✅ 타입 검사를 통과했습니다."
else
  echo "❌ 타입 오류가 발생했습니다."
  exit 1
fi

if npx lint-staged; then
  echo "✅ lint 규칙을 모두 통과했습니다."
else
  echo "❌ lint 규칙 오류가 발생했습니다."
  exit 1
fi